_prefs: 
  mapid: ruben.137cb812
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 138.1091
  - 36.0558
  - 8
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: Age POIS Japan
source: "mapbox:///mapbox.satellite,mapbox.mapbox-streets-v5,ruben.nodepoisjapan,ruben.waypoisjapan"
styles: 
  - style.mss
template: ''
